# This script defines functions for visualizing the best_video_games CSV file generated by the previous code.

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

def plot_games_by_genre():
    df = pd.read_csv('best_video_games.csv')
    df = df.dropna(subset=['Genre'])

    all_genres = []
    for genres in df['Genre']:
        split_genres = [g.strip() for g in genres.split(',')]
        all_genres.extend(split_genres)

    genre_counts = Counter(all_genres)
    genre_df = pd.DataFrame(genre_counts.items(), columns=['Genre', 'Count']).sort_values(by='Count', ascending=False)

    plt.figure(figsize=(10, 8))
    sns.barplot(x='Count', y='Genre', data=genre_df, palette='pastel')
    plt.title('Number of Best Video Games by Genre')
    plt.xlabel('Number of Games')
    plt.ylabel('Genre')
    plt.tight_layout()
    plt.show()

plot_games_by_genre()

def count_games_by_country():
    df = pd.read_csv('best_video_games.csv')
    order = df['HQ Location'].value_counts().index

    plt.figure(figsize=(12, 6))
    sns.countplot(x='HQ Location', data=df, order=order)
    plt.xticks(rotation=45, ha='right')
    plt.title('Best Video Games Worldwide (337 in Total)')
    plt.xlabel('Games\' Companies\' Location')
    plt.ylabel('Number of Games')
    plt.tight_layout()
    plt.show()

count_games_by_country()

def plot_games_by_5year_period():
    df = pd.read_csv('best_video_games.csv')

    df = df.dropna(subset=['Year'])
    df['Year'] = df['Year'].astype(int)
    df['5-Year Period'] = (df['Year'] // 5) * 5
    games_per_period = df['5-Year Period'].value_counts().sort_index()

    plt.figure(figsize=(12, 6))
    sns.barplot(x=games_per_period.index, y=games_per_period.values, palette='pastel')
    plt.xticks(rotation=45)
    plt.title('Number of Best Video Games Released Every 5 Years (337 in Total)')
    plt.xlabel('5-Year Period Start')
    plt.ylabel('Number of Games')
    plt.tight_layout()
    plt.show()

plot_games_by_5year_period()

def plot_games_by_platform():
    df = pd.read_csv('best_video_games.csv')
    df = df.dropna(subset=['Original platform'])

    all_platforms = []
    for platforms in df['Original platform']:
        split_platforms = [p.strip() for p in platforms.split(',')]
        all_platforms.extend(split_platforms)

    platform_counts = Counter(all_platforms)
    platform_df = pd.DataFrame(platform_counts.items(), columns=['Platform', 'Count']).sort_values(by='Count', ascending=False)

    plt.figure(figsize=(14, 7))
    sns.barplot(x='Platform', y='Count', data=platform_df, palette='pastel')
    plt.xticks(rotation=90)
    plt.title('Number of Best Video Games by Original Platform (337 in Total)')
    plt.xlabel('Platform')
    plt.ylabel('Number of Games')
    plt.tight_layout()
    plt.show()

plot_games_by_platform()